sudo: false

language: node_js
node_js: 10

after_failure:
  - chmod +x ./travis/webhook.sh
  - ./travis/webhook.sh

jobs:
    include:
      - stage: test

      - stage: build
        script: npm run build

      - stage: webhook
        install: skip
        script:
          - chmod +x ./travis/webhook.sh
          - ./travis/webhook.sh
