language: node_js
node_js:
    - 9
install: npm install
after_success: ./travis/webhook.sh
after_failure: ./travis/webhook.sh
jobs:
    include:
      - stage: test
        node_js: 9
        script: npm test
      - stage: build
        node_js: 9
        script: npm run build
